#!/usr/bin/env bash

git_completion_url=https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
git_prompt_url=https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

