#!/usr/bin/env bash

name='Victor van Poppelen'
email=vvanpo@gmail.com

repo=github.com/vvanpo/env
# Directories are relative to $HOME.
usr=.local
env="$usr/src/$repo"

github=https://raw.githubusercontent.com
git_completion=git/git/master/contrib/completion/git-completion.bash
git_prompt=git/git/master/contrib/completion/git-prompt.sh
includes=("$github/$git_completion" "$github/$git_prompt")

function install-dot {
    for file in $@; do
        rm -f ~/$file
        ln -s "$env/$file" ~/
    done
}

function install-bash {
    install-dot .bashrc .bash_profile .bash_logout
    mkdir -p ~/.bash

    cd ~/.bash
    for url in "${includes[@]}"; do
        curl -fsSLO "$url"
    done
    >/dev/null cd -

    . ~/.bashrc
}

function install-git {
    install-dot .gitignore
    rm -f ~/.gitconfig
    git config --global --add user.name "$name"
    git config --global --add user.email "$email"
    git config --global --add core.excludesfile '~/.gitignore'
}

install-dot .tmux.conf .vimrc
install-git
install-bash
