#!/usr/bin/env bash

repo=github.com/vvanpo/env

cd

while [[ -z $name ]]; do
    echo -n 'Full name: '
    read name
done

while [[ -z $email ]]; do
    echo -n 'E-mail: '
    read email
done

echo -n 'Local installation directory [~/.local]: '
read usr
usr="${usr:-.local}"
# We only strip home directory expansion after we've checked for empty input, to
# account for the edge-case of specifying ~/ as the install directory.
usr="${usr/#~\//}"
[[ -n $usr ]] && usr_prefix="$usr/"

env="${usr_prefix}src/$repo"
mkdir -p "$env"

if [[ -f $env/.git/config ]]; then
    remote=$(git config -f "$env/.git/config" --get remote.origin.url | grep "$repo.git")
    [[ -z $remote ]] && exit 1
    cd "$env"
    git checkout -q master
    git pull -q
    >/dev/null cd -
else
    git clone "https://$repo.git" "$env"
fi

$env/install "$name" "$email" "$usr"

if [[ ! -d $usr/bin ]] || [[ ! -e $usr/bin/update-env ]]; then
    mkdir -p "$usr/bin"
    ln -s "../src/$repo/pull" "$usr/bin/update-env"
fi

>/dev/null cd -
