#!/usr/bin/env bash

env_dir=~/.local/src/github.com/vvanpo/env

mkdir -p "$env_dir"

if [[ -f $env_dir/.git/config ]]; then
    if [[ -z $(git config -f "$env_dir/.git/config" --get remote.origin.url | grep "github.com/vvanpo/env.git") ]]; then
        exit 1
    fi
    cd "$env_dir"
    git checkout -q master
    git pull
    >/dev/null cd -
else
    git clone https://github.com/vvanpo/env.git "$env_dir"
fi

"$env_dir/install" -p
